spring:
  datasource:
    username: {{dbusername}}
    password: {{dbpassword}}
    #url: jdbc:mysql://{{dbhost}}:3306/{{dbname}}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    url: jdbc:mariadb://{{dbhost}}:3306/{{dbname}}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    
    


## jdbc:mariadb://{{dbhost}}:3306/{{dbname}}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
## Hibernate Properties

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect 
        
        # org.hibernate.dialect.MySQL5InnoDBDialect
        # org.hibernate.dialect.MariaDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
