spring:
  datasource:

    url: jdbc:mysql://{{dbhost}}:3307/{{dbname}}?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: {{dbusername}}
    password: {{dbpassword}}


## Hibernate Properties

# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
